name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential netcat-openbsd
    
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        export VCPKG_ROOT=$(pwd)/vcpkg
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
    
    - name: Build project
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
        cmake --build ./build
    
    - name: Run basic tests
      run: |
        python3 test_basic.py
    
    - name: Run advanced tests
      run: |
        python3 test_advanced.py

  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential netcat-openbsd
    
    - name: Install dependencies (macOS) 
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake netcat
    
    - name: Install vcpkg (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        export VCPKG_ROOT=$(pwd)/vcpkg
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
    
    - name: Install vcpkg (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        export VCPKG_ROOT=$(pwd)/vcpkg
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
    
    - name: Build project
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
        cmake --build ./build
    
    - name: Verify build artifacts
      run: |
        ls -la build/server
        file build/server